### ISSUE TITLE
FEATURE add checkbox options for HTML5 video attributes

### ISSUE THREAD

**Issue by korthjp17** [dynamic/silverstripe-elemental-video#1]
- [ ] Autoplay
- [ ] Muted
- [ ] Loop

**Comment by muskie9** [comment]
What would the desired defaults for these be in your opinion?

**Comment by korthjp17** [comment]
I'm just going to default them to not be used. But, it could be helpful, especially muted and plays inline - some of the mobile browsers won't do the autoplay unless those options are also set
